language: go
go:
  - 1.3

install:
  - go get -t -v ./...
  - mkdir -p $HOME/gopath/bin
  - go install -v github.com/onsi/ginkgo/ginkgo
  - curl -L https://github.com/coreos/etcd/releases/download/v2.0.0/etcd-v2.0.0-linux-amd64.tar.gz | tar zxf - -C /tmp
  - mv /tmp/etcd-v2.0.0-linux-amd64/etcd $HOME/gopath/bin

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - ginkgo -r --randomizeAllSpecs --failOnPending -race
