language: go
go:
  - 1.2

install:
  - go get -v ./...
  - mkdir -p $GOPATH/bin
  - go install -v github.com/onsi/ginkgo/ginkgo
  - pushd ../../coreos/etcd
  - ./build
  - mv ./etcd $GOPATH/bin
  - popd
  - mkdir -p $HOME/bin
  - pushd $HOME/bin
  - curl -C - http://apache.osuosl.org/zookeeper/zookeeper-3.4.5/zookeeper-3.4.5.tar.gz | tar -zx
  - mv $HOME/bin/zookeeper-3.4.5 $HOME/bin/zookeeper
  - chmod a+x $HOME/bin/zookeeper/bin/zkServer.sh
  - popd

script:
  - export PATH=$HOME/bin/zookeeper/bin:$GOPATH/bin:$PATH 
  - ginkgo -r -i --randomizeAllSpecs --failOnPending
